$terminal = kitty
$fileManager = thunar
$webBrowser = firefox

bind = Super, 0, exec, quickshell
bind = Super, 9, exec, pkill quickshell

# Launchers
bind = SUPER, P, exec, qs ipc call launcher toggle
bind = Super, return, exec, $terminal # Open the terminal
bind = Super, Q, killactive # Close selected window
bind = Super, W, exec, $webBrowser # Open web browser
bind = Super, E, exec, $fileManager # Open file manager
bind = Super, tab, exec, kitty -e nvim # Open Neovim
bind = Super, Z, exec, zed # Open Zed
# Windows flow
bind = Super, S, togglesplit, #dwindle
bind = Super, F, togglefloating, # Float active window
bind = Super, left, movefocus, l
bind = Super, right, movefocus, r
bind = Super, up, movefocus, u
bind = Super, down, movefocus, d

bindm = Super, mouse:272, movewindow # Move windows using mouse
bindm = Super, mouse:273, resizewindow # Resize windows using the mouse

# Hyprshot
bind = Super, PRINT, exec, hyprshot -m window
bind = , PRINT, exec, hyprshot -m region
bind = SHIFT, PRINT, exec, hyprshot -m output

# Workspaces
bind = Super, 1, workspace, 1
bind = Super, 2, workspace, 2
bind = Super, 3, workspace, 3
bind = Super, 4, workspace, 4
bind = Super, 5, workspace, 5

bind = Super SHIFT, 1, movetoworkspace, 1
bind = Super SHIFT, 2, movetoworkspace, 2
bind = Super SHIFT, 3, movetoworkspace, 3
bind = Super SHIFT, 4, movetoworkspace, 4
bind = Super SHIFT, 5, movetoworkspace, 5

# Hyprctl
bind = Super, M, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
