# Execs
# exec-once = waybar
# exec-once = hyprpaper
# exec-once = hyprlauncher -d
exec-once = qs
exec-once = awww-daemon && awww img ~/.config/quickshell/assets/building_cyber.jpg

# Cursor
env = HYPRCURSOR_THEME,macOS
env = HYPRCURSOR_SIZE,20
env = XCURSOR_THEME,macOS
env = XCURSOR_SIZE,20

# Portals
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

# Sources
source = ~/.config/hypr/modules/keybinds.conf
source = ~/.config/hypr/modules/monitors.conf

# Hyprshot
env = HYPRSHOT_DIR,$HOME/Pictures/Screenshots

general {
	locale = en_US
	layout = dwindle

	# Borders
	border_size = 1
	gaps_in = 5
	gaps_out = 10 
	
	col.active_border = rgba(F7DCDE39)
	col.inactive_border = rgba(A58A8D30)
}

dwindle {
	force_split = 2 # Where windows will open -> 0 for cursor location, 1 for left side, 2 for right side
}

# Inputs
input {
	kb_layout = br
	kb_model = abnt2
}

# Decoration
decoration {
	rounding_power = 2 # Windows rounding
	rounding = 15 # Windows rounding
}
